services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/workspace/backend
      - /workspace/backend/.venv
    environment:
      - PATH=/workspace/backend/.venv/bin:$PATH
      - PYTHONPATH=/workspace/backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/workspace/frontend:cached
      - node_modules_volume:/workspace/frontend/node_modules
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - backend/.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  node_modules_volume:
