"""add weather_api_key

Revision ID: db2328e48cd3
Revises:
Create Date: 2025-06-23 10:58:45.640295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2328e48cd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'weather_api_key' not in columns:
        op.add_column('users', sa.Column('weather_api_key', sa.String(length=64), nullable=True))
        op.create_unique_constraint(None, 'users', ['weather_api_key'])
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'weather_api_key')
    # ### end Alembic commands ###
